<a href="https://colab.research.google.com/github/thng2024/HOC_UPGRAD/blob/main/Pandas_with_Rajan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Pandas ? üêº
---

Pandas is a powerful and easy to use library , primarily used for Data Analysis.
<pre>
Using Pandas we Can do

  ‚û°Ô∏è Data PreProcessing / Cleaning (Primary)
  ‚û°Ô∏è Data Manipulation
  ‚û°Ô∏è Data Analysis (Primary)

Similar to Numpy , Pandas also Provides its OWN Data Structure
<pre>
      for STORING & Processing DATA.

      these are

            ‚≠ê Series
            ‚≠ê DataFrame

## When to Use Series & WHen to Use Dataframe ‚ùì
---

‚≠ê Series : It is used to Store , Process and Analyse 1D or Linear Data eg. List in Python.

‚≠ê DataFrame : It is used to Store, Process and Analyse 2D or Tabular Data eg. SHeet in Excel.

In [ ]:
#  Name         age       course
#  --------------------------
#  Miki         22         php
#  zhining      23         java
#  armanta      21         cSharp

# ü™ª Working with Series
---

In [ ]:
# first, you must import pandas

import pandas as pd

In [ ]:
# here is a sample List

stockPrices = [ 44.5 , 22.1 , 77.4 , 99.5 , 67.4 ]

üçé In Order to Have Access to Built in Analytical Functions of Pandas , I Must Convert List into Series using pd.Series() Function.

In [ ]:
mySeries = pd.Series ( stockPrices )            #<------------------üçé

In [ ]:
# what is mySeries ?
print( type(mySeries) )

<class 'pandas.core.series.Series'>

In [ ]:
# what does mySeries Contains ?
mySeries

0    44.5
1    22.1
2    77.4
3    99.5
4    67.4
dtype: float64

# üí° Quick Fact : Pandas uses ND Array Internally to Store Data.

(Pandas is Built On Top of Numpy)

In [ ]:
mySeries.values

array([44.5, 22.1, 77.4, 99.5, 67.4])

In [ ]:
type(mySeries.values)

numpy.ndarray

In [ ]:
# pandas has Access to ND Array Data Structure Functionalites Only and not Numpy.

In [ ]:
mySeries.max()

99.5

In [ ]:
mySeries.sum()

310.9

# üíª Creating or Working with DataFrame
---

Dataset Link :
NBA : üèÄ

https://drive.google.com/file/d/1ZaNh_kZ5fIV7iXx350dDS2UbnSiJoRsD/view?usp=sharing

üí°pd.read_csv() : this function is used to read a CSV file and returns a DataFrame.

In [ ]:
nba = pd.read_csv('nba.csv')

In [ ]:
# what is nba ?
print( type(nba))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
# what nba contains ?
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# üíª Let Us Learn How to Do DataFrame Inspection !
---

In [ ]:
# how many Rows X Cols are there ?
nba.shape

(458, 9)

In [ ]:
# column titles
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [ ]:
# columns & DataTypes
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

üí° Please Note: Object DataType in Pandas Represents String Data.
(String isn't available in Pandas we Use Object Instead)

In [ ]:
# .Describe() : this method returns statistical or numerical Facts for all the numerical Columns Present in DataFrame.

nba.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [ ]:
# .info(): this method returns the detailed summary of dataframe
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

Column Name | Count of Values Present in Column
---
![image.png]()

In [ ]:
# this expression returns the count of missing values in each column! (is this mathematics or analysis)
nba.isna().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [ ]:
# head() : this function returns the first 5 Rows
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [ ]:
# tail():  this function returns the last five rows
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# üí° Quick Fact : NaN in Pandas Represents the Missing or Absent Value.

In [ ]:
# you can also specify count of rows

nba.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

# üíª Accessing a Single Column
---

In [ ]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [ ]:
# Syntax1 : <DataFrame>.ColumnName
nba.Name.head()

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object

In [ ]:
# Syntax2 : <DataFrame>[ColumnName]
nba['Name'].head()

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object

üòï What is the difference in Both Syntax?
---
<pre>
answer: you cannot access column where titles are having spaces using (dot) Expression.

eg.

assuming there is a column named 'my college'

nba.my college      ‚ùå

nba['my college']   ‚úÖ

In [ ]:
# let us do a small practical

In [ ]:
# Adding A new Column

nba['my sport'] = 'Basketball'

In [ ]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,my sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Basketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Basketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Basketball
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Basketball
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Basketball

In [ ]:
nba.my sport

SyntaxError: invalid syntax (<ipython-input-34-5afbc817236b>, line 1)

In [ ]:
nba['my sport']

0      Basketball
1      Basketball
2      Basketball
3      Basketball
4      Basketball
          ...
453    Basketball
454    Basketball
455    Basketball
456    Basketball
457    Basketball
Name: my sport, Length: 458, dtype: object

In [ ]:
# here is how we Delete the column!

del nba['my sport']

In [ ]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

# üíª  Accessing Multiple Columns
---

In [ ]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [ ]:
# 1: define a  list containing choice of columns.
mycols = ['Name' ,'College','Salary']
# 2. pass list withing square brackets in DataFrame
nba[ mycols ].head()

            Name            College     Salary
0  Avery Bradley              Texas  7730337.0
1    Jae Crowder          Marquette  6796117.0
2   John Holland  Boston University        NaN
3    R.J. Hunter      Georgia State  1148640.0
4  Jonas Jerebko                NaN  5000000.0

In [ ]:
# Here is how Direct Expression Looks Like
nba[ ['Name','College','Salary']].head()

            Name            College     Salary
0  Avery Bradley              Texas  7730337.0
1    Jae Crowder          Marquette  6796117.0
2   John Holland  Boston University        NaN
3    R.J. Hunter      Georgia State  1148640.0
4  Jonas Jerebko                NaN  5000000.0

# üíª Filtering Rows (Important)
---

In [ ]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

üçé you are Asked to find all Players from 'Texas' College.

In [ ]:
# 1. create condition
c1 = nba.College == 'Texas'
# 2. Pass condition into DataFrame
nba[ c1 ]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
289,Jordan Hamilton,New Orleans Pelicans,25.0,SG,25.0,6-7,220.0,Texas,1015421.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0

In [ ]:
# Here is how you can do it using Direct Expression
nba[    nba.College == 'Texas' ]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
289,Jordan Hamilton,New Orleans Pelicans,25.0,SG,25.0,6-7,220.0,Texas,1015421.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0

# üèÜ You are asked to Find Only Players who are 25 or Younger
---

üí° Creating DataFrame for Simplifying Problem Solving is Suggested !

In [ ]:
youngPlayers = nba[ nba.Age <=25 ]

In [ ]:
# count of rows
len(youngPlayers)     # or younPlayers.shape

199

# üíª Handling Multiple Conditions
---

In [ ]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

üèÜ You are Aksed to Find Players from 'Texas' College Playing from 'PG' Position.

In [ ]:
c1 = nba.College  == 'Texas'
c2 = nba.Position == 'PG'

nba[ c1 & c2 ]             # Here & is Logical AND

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0

In [ ]:
# here is how you do it using Direct Expression

nba[  (nba.College == 'Texas') & (nba.Position == 'PG' ) ]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0

# üèÜ  You are Asked to Find players from 'Toronto Raptors' Team and are 25 or Younger.
---